### ISSUE TITLE
stormpath namespace for stormpath config file

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-spec#17]
In our current spec [here](https://github.com/stormpath/stormpath-sdk-spec/blob/master/specifications/config.md#default-configuration), we do not prefix the properties with the `stormpath` namespace/key.

This causes problems when stormpath.yaml is read within the context of other YAML files.  For applications that support yaml for config already, the above config should look like this instead:

``` yaml
stormpath:
  client:
    apiKey:
      file: null
      id: null
      secret: null
    cacheManager:
      defaultTtl: 300
      defaultTti: 300
      caches: { }
    baseUrl: "https://api.stormpath.com/v1"
    connectionTimeout: 30
    authenticationScheme: "SAUTHC1"
    proxy:
      port: null
      host: null
      username: null
      password: null
  application:
    name: null
    href: null
```

This allows you to take your Stormpath config and copy and paste it into existing yaml configs because the config is namespaced appropriately.

Any thoughts around this?
